### ISSUE TITLE
Can't import the named export 'LIST_NEST_MODE_HTML' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by JGuest777** [portabletext/react-portabletext#7] opened 2022-03-14 21:19 UTC
Not able to import into Nextjs app:

node -v: 14.18.1
yarn -v: 1.22
react: 17.0.1

**Comment by Livelyguy00** [comment] 2022-03-18 23:57
The same for me in React app based on CRA

**Comment by rexxars** [comment] 2022-03-20 03:14
I cannot reproduce this. Which versions of the module are you using?

Minimal next.js page:
```js
import {PortableText} from '@portabletext/react'

const Home = () => {
  return (
    <PortableText value={
      [{
        _type: 'block',
        children: [{_type: 'span', text: 'Hello from Portable Text.'}]
      }]
    } />
  )
}

export default Home
```

Minimal create react app:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import {PortableText} from '@portabletext/react';

ReactDOM.render(
  <React.StrictMode>
    <PortableText value={
      [{
        _type: 'block',
        children: [{_type: 'span', text: 'Hello from Portable Text.'}]
      }]
    } />
  </React.StrictMode>,
  document.getElementById('root')
);
```

**Comment by holdercp** [comment] 2022-03-20 14:53
This is happening for me as well. Using the [Gatsby Blog Starter](https://github.com/sanity-io/sanity-template-gatsby-blog) pulled down in April 2020.

`"react": "16.13.1"`
`"gatsby": "2.24.49"`
 
It's attempting to use the `.mjs` export since I'm using ESM import/export syntax in the project.

Here is the error when building:
```sh
ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'LIST_NEST_MODE_HTML' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'buildMarksTree' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'createContext' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'isPortableTextBlock' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'isPortableTextListItemBlock' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'isPortableTextToolkitList' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'isPortableTextToolkitSpan' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'isPortableTextToolkitTextNode' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'nestLists' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'spanToPlainText' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'useContext' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web:  ERROR #98123  WEBPACK
web: Generating development JavaScript bundle failed
web: Can't reexport the named export 'toPlainText' from non EcmaScript module (only default export is available)
web: File: node_modules/@portabletext/react/dist/react-portable-text.mjs
web: failed Re-building development bundle - 0.205s
```

**Comment by geoffreyjball** [comment] 2022-04-02 23:24
@JGuest777 What version of next are you running and what do you see when you run `npm ls webpack`?

**Comment by JGuest777** [comment] 2022-04-03 14:18
next v10.0.6
that npm command returns (empty)

Will upgrade to canary.6 and try!

**Comment by geball** [comment] 2022-04-03 16:02
Thanks for confirming. If I was on the right track then `v10.0.6` should have worked fine, so I suspect something else. I'll keep looking.

**Comment by geball** [comment] 2022-04-03 17:56
@holdercp For your case, it might be related to the version of React. It appears [React >= 17](https://github.com/portabletext/react-portabletext/blob/main/MIGRATING.md#no-container-rendered) is required.

**Comment by carlosganzerla** [comment] 2022-04-27 20:46
@red-runner Found the solution [here](https://github.com/storybookjs/storybook/issues/16690#issuecomment-971579785) for Storybook. Worked for me.

**Comment by red-runner** [comment] 2022-05-02 06:36
> 

Nice one @carlosganzerla worked for me!! 🥇 💐

**Comment by Livelyguy00** [comment] 2022-06-06 20:04
node -v: 16.15.0
npm -v: 8.5.5
react: 17.0.2
Still the same for me

**Comment by dorelljames** [comment] 2022-07-22 01:53
I've spin up a [codesandbox](https://codesandbox.io/s/inspiring-mclean-rdbnvf?file=/src/App.js) here for an old CRA but I can't replicate the issue, however, I can just like others here in my local setup. Probably something to do with other packages or a mixed of other commonjs requires. Idk.

**Comment by JKarlavige** [comment] 2023-02-06 15:43
I ran into this issue with version `1.0.6` of `@portabletext/react`. Upgrading to `2.0.1` resolved the issue. Full error I was receiving:

```
Server Error

SyntaxError: Named export 'LIST_NEST_MODE_HTML' not found. The requested module '@portabletext/toolkit' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@portabletext/toolkit';
const { nestLists, LIST_NEST_MODE_HTML, isPortableTextToolkitList, isPortableTextListItemBlock, isPortableTextToolkitSpan, spanToPlainText, isPortableTextBlock, isPortableTextToolkitTextNode, buildMarksTree } = pkg;
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
node_modules/@portabletext/react/dist/react-portable-text.mjs (32)
ModuleJob._instantiate
node:internal/modules/esm/module_job (123:21)
async ModuleJob.run
node:internal/modules/esm/module_job (189:5)
async ESMLoader.import
node:internal/modules/esm/loader (530:24)
async importModuleDynamicallyWrapper
node:internal/vm/module (438:15)
```

**Comment by rexxars** [comment] 2023-02-08 12:22
Should be fixed in the latest versions - please leave a comment if you're still having issues with the 2.x version.

**Closed by rexxars** 2023-02-08 12:22 UTC
